apiVersion: v2
appVersion: "0.174.0"
description: Node-based Workflow Automation Tool
name: n8n
type: application
version: 0.174.0
kubeVersion: ">=1.16.0-0"
keywords:
  - n8n
  - workflow
maintainers:
  - name: William Bartholomew
    email: wdb@willbar.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.0
  - name: postgresql
    version: 11.1.25
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
