apiVersion: v2
appVersion: "1.16.0"
description: Node-based Workflow Automation Tool
name: n8n
type: application
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - n8n
  - workflow
maintainers:
  - name: William Bartholomew
    email: wdb@willbar.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - name: postgresql
    version: 10.14.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
