#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: n8nio/n8n
  # -- image tag
  tag: "0.174.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [changedetection-io documentation](https://changedetection-io.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5678

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    # storageClass: ""
    # size: 1Gi
    mountPath: /home/node/.n8n

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See values.yaml
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: n8n
    username: n8n
    password: n8n-pass
    rootPassword: n8nrootpass
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 5Gi

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  image:
    repository: bitnami/postgresql
    tag: 14.1.0
  postgresqlUsername: n8n
  postgresqlPassword: n8n-pass
  postgresqlDatabase: n8n
  persistence:
    enabled: false
    # storageClass: ""
    # size: 5Gi
