apiVersion: v1
kind: Service
metadata:
  name: {{ include "elastiflow.fullname" . }}
  labels:
    {{- include "elastiflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 9995
      protocol: UDP
      name: flow
  selector:
    {{- include "elastiflow.selectorLabels" . | nindent 4 }}
