# https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
# https://stackoverflow.com/questions/10234327/convert-bash-ls-output-to-json-array/
name: Build
on: push
jobs:
  discover-charts:
    name: Discover Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build-chart:
    name: Build Chart
    runs-on: ubuntu-latest
    needs: discover-charts
    permissions:
      contents: read
    strategy: 
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.discover-charts.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: helm package -u ${{ matrix.chart }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chart }}
          path: *.tgz
